package com.pichincha.riesgos.libranzasrg;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("EMPRESA")
@org.kie.api.definition.type.Description("Informacion relacionada a la empresa donde se efectua el convenio para ofrecer el producto Libranzas")
public class EMPRESA implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Description(value = "Indica si la empresa en publica o privada. Los valores son:\nPUBLICA\nPRIVADA")
   @org.kie.api.definition.type.Label(value = "TIPO")
   private java.lang.String TIPO;
   @org.kie.api.definition.type.Description(value = "El convenio celebrado entre el banco y la empresa donde se ofrecera el producto libranza.")
   @org.kie.api.definition.type.Label(value = "CONVENIO")
   private java.lang.String CONVENIO;

   public EMPRESA()
   {
   }

   public java.lang.String getTIPO()
   {
      return this.TIPO;
   }

   public void setTIPO(java.lang.String TIPO)
   {
      this.TIPO = TIPO;
   }

   public java.lang.String getCONVENIO()
   {
      return this.CONVENIO;
   }

   public void setCONVENIO(java.lang.String CONVENIO)
   {
      this.CONVENIO = CONVENIO;
   }

   public EMPRESA(java.lang.String TIPO, java.lang.String CONVENIO)
   {
      this.TIPO = TIPO;
      this.CONVENIO = CONVENIO;
   }

}