package com.pichincha.riesgos.libranzasrg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EMPRESA implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public EMPRESA() {
    }

}